<?php
$newdate = strtotime('+1 day', strtotime(date('Y-m-d 00:00:00')));
$date = date('Y-m-d 00:00:00', $newdate);

$_objectManager = \Magento\Framework\App\ObjectManager::getInstance();

$productCollection = $_objectManager->create('Magento\Catalog\Model\ResourceModel\Product\CollectionFactory');

$collection  = 	$productCollection->create()
				->addAttributeToSelect('*')
				->addAttributeToFilter('start_date', ['eq'=>$date])
				->load();
?>

<table cellspacing="0" cellpadding="10" border="0" style="width:100%;">
	<thead>
		<tr>
			<th style="background-color:#363636;color:#fff;font-size:13px;font-weight:normal!important;padding:5px 9px 6px 9px;border:solid 1px #ccc;">No</th>
			<th style="background-color:#363636;color:#fff;font-size:13px;font-weight:normal!important;padding:5px 9px 6px 9px;border:solid 1px #ccc;">SKU</th>
			<th style="background-color:#363636;color:#fff;font-size:13px;font-weight:normal!important;padding:5px 9px 6px 9px;border:solid 1px #ccc;">Product</th>
			<th style="background-color:#363636;color:#fff;font-size:13px;font-weight:normal!important;padding:5px 9px 6px 9px;border:solid 1px #ccc;">Status</th>
			<th style="background-color:#363636;color:#fff;font-size:13px;font-weight:normal!important;padding:5px 9px 6px 9px;border:solid 1px #ccc;">Start Date</th>
			<th style="background-color:#363636;color:#fff;font-size:13px;font-weight:normal!important;padding:5px 9px 6px 9px;border:solid 1px #ccc;">End Date</th>
		</tr>
	</thead>
	<tbody>
		<?php foreach ($collection as $key=>$product): ?>
			<tr>
				<td style="background-color:#f1f1f1;color:#000;padding:10px!important;border:solid 1px #ccc;text-align:center;vertical-align: middle!important;font-size: 12px!important;"><?= $key?></td>
				<td style="background-color:#f1f1f1;color:#000;padding:10px!important;border:solid 1px #ccc;text-align:center;vertical-align: middle!important;font-size: 12px!important;"><?= $product->getSku();?></td>
				<td style="background-color:#f1f1f1;color:#000;padding:10px!important;border:solid 1px #ccc;text-align:center;vertical-align: middle!important;font-size: 12px!important;"><?= $product->getName();?></td>
				<td style="background-color:#f1f1f1;color:#000;padding:10px!important;border:solid 1px #ccc;text-align:center;vertical-align: middle!important;font-size: 12px!important;"><?= ($product->getSchedulerStatus() == 1)? 'Enable' : 'Disable' ?></td>
				<td style="background-color:#f1f1f1;color:#000;padding:10px!important;border:solid 1px #ccc;text-align:center;vertical-align: middle!important;font-size: 12px!important;">
					<?= date('Y-m-d', strtotime($product->getStartDate()));?> <?= $starttime = ($product->getStartTime() != null) ? $product->getStartTime().':00' : '00:00'; ?>
				</td>
				<td style="background-color:#f1f1f1;color:#000;padding:10px!important;border:solid 1px #ccc;text-align:center;vertical-align: middle!important;font-size: 12px!important;">
					<?= date('Y-m-d', strtotime($product->getEndDate()));?> <?= $endtime = ($product->getEndTime() != null) ? $product->getEndTime().':00' : '00:00'; ?>		
				</td>
			</tr>
		<?php endforeach; ?>
	</tbody>
</table>